# Site settings
name: Samuel Johnson
title: Scientist / Engineer - SC
# email: my short first name (six letters) at Physical Research Laboratory’s domain (prl [dot] res [dot] in)
organisation: Physical Research Laboratory
username: samueljohnson
description: "This page is created using git, jekyll, markdown, vim and other open-source software."
baseurl: ""
url: "samueljohnson.io"

comments :
  provider : disqus
  disqus :
    short_name : samueljohnson

# Build settings
markdown: kramdown
#permalinks: pretty
permalink: /blog/:year/:month/:day/:title/
gems:
          - jekyll-sitemap
