# Site settings
name: Samuel Johnson
title: Scientist / Engineer - SC
# email: samuel [at] prl.res.in
organisation: Physical Research Laboratory
username: samueljohnson
description: "This site is created using git, vim, jekyll, markdown, pygments, liquid and other FOSS."
baseurl: ""
url: "samueljohnson.github.io"

comments :
  provider : disqus
  disqus :
    short_name : samueljohnson

# Build settings
markdown: kramdown
#permalinks: pretty
permalink: /:year/:month/:title/
gems:
          - jekyll-sitemap
