# Site settings
name: Samuel Johnson
title: Scientist / Engineer - SC
# email: samuel [at] prl.res.in
organisation: Physical Research Laboratory
username: samueljohnson
description: "This site is created using git, vim, jekyll, markdown, liquid and other FOSS."
baseurl: ""
url: "samueljohnson.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
